/* global window, navigator, getComputedStyle */
import {chromium,expect} from '@playwright/test';
import {editingFixture} from './editing-fixture.mjs';
import assert from 'node:assert/strict';
import {join} from 'node:path';
import {writeFile} from 'node:fs/promises';
const fixture=await editingFixture({deep:true}),browser=await chromium.launch(),report=[];
async function menu(p,id,action){const control=p.locator(`[id="edit-folder-${id}"], [id="edit-bookmark-${id}"]`);await control.evaluate(n=>n.parentElement.querySelector('.item-actions > button').click());await p.getByRole('menuitem',{name:action,exact:true}).click();}
async function titleDrag(p,source,target,fraction=.1){await source.scrollIntoViewIfNeeded();const a=await source.evaluate(n=>{const r=[...n.getClientRects()].filter(r=>r.width>0).at(-1);return {x:r.left+Math.min(20,r.width/2),y:r.top+r.height/2}});await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(a.x+12,a.y+2,{steps:3});const b=await target.evaluate(n=>{const r=n.matches('.folder-title')?n.getBoundingClientRect():[...n.getClientRects()].filter(r=>r.width>0).at(-1);return {x:r.left,y:r.top,width:r.width,height:r.height}});await p.mouse.move(b.x+b.width*fraction,b.y+b.height/2,{steps:12});await p.waitForTimeout(70);}
try{for(const theme of ['light','dark']){
 const c=await browser.newContext({viewport:{width:1250,height:850},colorScheme:theme}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto(fixture.url);
 for(const mode of ['browse','edit']){if(mode==='edit')await p.locator('#catalogue-edit').click();const sizes=await p.locator('.catalogue-navigation button').evaluateAll(ns=>ns.filter(n=>!n.closest('.item-menu')).map(n=>getComputedStyle(n).fontSize));assert(sizes.every(s=>s==='12px'),JSON.stringify(sizes));}
 await expect(p.getByRole('button',{name:'Manage',exact:true})).toHaveCount(0);await p.getByRole('button',{name:'New',exact:true}).click();await expect(p.getByRole('menuitem',{name:'New favorite'})).toHaveCSS('text-transform','none');await expect(p.getByRole('menuitem',{name:'New favorite'})).toHaveCSS('letter-spacing','normal');await p.screenshot({path:join(fixture.output,`${theme}-new-menu.png`)});await p.keyboard.press('Escape');
 // Responsive root selection keeps full names and keyboard order; no hidden tab stops.
 await p.getByRole('button',{name:'All bookmarks',exact:true}).focus();await p.setViewportSize({width:390,height:850});await expect(p.locator('.root-selector')).toBeVisible();await expect(p.locator('.root-selector')).toBeFocused();await p.keyboard.press('Alt+2');await expect(p.locator('.root-selector')).toHaveValue('r1');await p.locator('.root-selector').selectOption('r2');await expect(p.locator('.root-selector')).toHaveValue('r2');await p.getByRole('button',{name:'Search /'}).click();const search=p.getByRole('textbox',{name:'Search bookmarks',exact:true});await search.fill('ordinary');await search.evaluate(n=>n.setSelectionRange(1,4));await p.keyboard.press('Alt+1');await expect(search).toBeFocused();assert.deepEqual(await search.evaluate(n=>[n.selectionStart,n.selectionEnd]),[1,4]);await p.keyboard.press('Escape');await expect(p.locator('.root-selector')).toHaveValue('r2');await p.screenshot({path:join(fixture.output,`${theme}-compact-roots.png`)});await p.locator('.root-selector').selectOption('*');await p.locator('.root-selector').focus();await p.setViewportSize({width:1250,height:850});await expect(p.getByRole('button',{name:'All bookmarks',exact:true})).toBeFocused();await p.keyboard.type('ordinary');await expect(search).toHaveValue('ordinary');await p.setViewportSize({width:390,height:850});await p.keyboard.press('Escape');await expect(p.locator('.root-selector')).toBeFocused();await p.setViewportSize({width:1250,height:850});
 // Enter submits a field, but focused Cancel stays Cancel. Escape returns intact draft.
 await p.getByRole('button',{name:'New',exact:true}).click();await p.getByRole('menuitem',{name:'New favorite'}).click();await expect(p.locator('#create-url')).toHaveJSProperty('tagName','INPUT');await c.grantPermissions(['clipboard-read','clipboard-write']);await p.locator('#create-url').fill('');await p.evaluate(()=>navigator.clipboard.writeText('javascript:alert(1)\n//code'));await p.locator('#create-url').focus();await p.keyboard.press('Control+V');await expect(p.locator('#create-url')).toHaveValue('');await expect(p.getByRole('alert')).toContainText('Multiline bookmarklet paste was not applied');await p.locator('#create-title').fill('Disposable new');await p.locator('#create-url').fill('https://example.test/line');await p.locator('#create-parent').selectOption('s0');await p.locator('#create-title').focus();await p.keyboard.press('Escape');await p.keyboard.press('Escape');await expect(p.locator('#create-title')).toHaveValue('Disposable new');await p.keyboard.press('Enter');await expect(p.locator('dialog')).toHaveCount(0);
 await p.locator('#edit-bookmark-created-1').click();await expect(p.locator('#favorite-edit-url')).toHaveJSProperty('tagName','INPUT');await p.getByRole('button',{name:'Cancel',exact:true}).focus();await p.keyboard.press('Enter');await expect(p.locator('dialog')).toHaveCount(0);
 await menu(p,'created-1','Move…');await expect(p.locator('#move-position option')).toHaveCount(22);assert.deepEqual((await p.locator('#move-position option').allTextContents()).slice(0,2),['Start','End']);assert(!(await p.locator('#move-position option').allTextContents()).some(t=>t.startsWith('After')));await p.screenshot({path:join(fixture.output,`${theme}-move-dialog.png`)});await p.locator('#move-parent').focus();await p.keyboard.press('Space');await p.keyboard.press('Escape');await expect(p.locator('dialog')).toHaveCount(1);await p.keyboard.press('Escape');await expect(p.locator('dialog')).toHaveCount(0);
 // Safe destructive initial focus; Enter on Cancel cannot delete.
 await menu(p,'created-1','Delete…');await expect(p.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();await p.keyboard.press('Enter');await expect(p.locator('dialog')).toHaveCount(0);await expect(p.locator('#bookmark-created-1')).toBeVisible();
 await menu(p,'s0','Delete…');await expect(p.locator('dialog')).toContainText('2 descendant folders and 23 favorites');await p.evaluate(()=>window.external('0-0',{title:'Changed during confirmation'}));await expect(p.getByRole('button',{name:'Delete',exact:true})).toBeDisabled();await p.getByRole('button',{name:'Review updated summary'}).click();await expect(p.getByRole('button',{name:'Delete',exact:true})).toBeEnabled();await p.screenshot({path:join(fixture.output,`${theme}-delete-confirmation.png`)});await p.getByRole('button',{name:'Cancel',exact:true}).click();
 // Title drag from a wrapped final line, canonical End outside all actions.
 await p.evaluate(()=>window.external('0-0',{title:'A very long wrapping favorite title with many ordinary words and a_long_filename_that_wraps.pdf'}));await p.setViewportSize({width:600,height:850});await p.evaluate(async()=>{await window.external('0-0',{parentId:'s0'});await window.external('created-1',{parentId:'s0'});});await p.waitForTimeout(200);const source=p.locator('#bookmark-0-0');const target=p.locator('#bookmark-created-1');await target.scrollIntoViewIfNeeded();await titleDrag(p,source,target,.60);await expect(p.locator('.drag-status')).toContainText('End of');const cue=await p.locator('.drag-cue').boundingBox(),ending=await p.locator('[data-item-id="created-1"] .extra-actions').boundingBox();assert(cue.x>=ending.x+ending.width);await p.screenshot({path:join(fixture.output,`${theme}-end-marker.png`)});await p.keyboard.press('Escape');await p.mouse.up();await expect(p.locator('.drag-cue')).toHaveCount(0);assert.equal(p.url(),fixture.url);
 assert.equal(await p.locator('.drag-handle').evaluateAll(ns=>ns.some(n=>n.tabIndex>=0||n.tagName==='BUTTON')),false);
 // A title click still toggles; no post-drag click toggles the source section.
 await p.setViewportSize({width:1250,height:850});await p.locator('[id="section-folder:s0"]').click();await expect(p.locator('[id="section-folder:s0"]')).toHaveAttribute('aria-expanded','false');await p.locator('[id="section-folder:s0"]').click();await expect(p.locator('[id="section-folder:s0"]')).toHaveAttribute('aria-expanded','true');
 await titleDrag(p,p.locator('#bookmark-0-1'),p.locator('#folder-f0 .folder-title'),.5);await expect(p.locator('.drag-status')).toContainText('Move inside');await p.mouse.up();await expect.poll(()=>p.evaluate(async()=>(await window.service.snapshot('check')).favorites.find(f=>f.id==='0-1').parentId)).toBe('f0');assert.equal(p.url(),fixture.url);
 await menu(p,'created-1','Delete…');await p.evaluate(()=>window.failDelete=true);await p.getByRole('button',{name:'Delete',exact:true}).click();await expect(p.getByRole('alert')).toContainText('0 native item(s) DELETED');await p.evaluate(()=>window.failDelete=false);await p.getByRole('button',{name:'Delete',exact:true}).click();await expect(p.locator('dialog')).toHaveCount(0);await expect(p.locator('#bookmark-created-1')).toHaveCount(0);
 await menu(p,'f0','Delete…');await p.getByRole('button',{name:'Delete',exact:true}).click();await expect(p.locator('dialog')).toHaveCount(0);assert.equal(await p.evaluate(async()=>(await window.service.snapshot('check')).folders.some(f=>f.id==='f0')),false);assert.equal(await p.evaluate(async()=>(await window.service.snapshot('check')).favorites.some(f=>f.id==='n0')),false);await expect(p.locator('#catalogue-edit')).toHaveAttribute('aria-pressed','true');
 // Whole section titles use a single End marker at the sheet boundary.
 await p.setViewportSize({width:1250,height:1100});await p.mouse.move(1240,400);await p.mouse.wheel(0,550);await p.waitForTimeout(180);await titleDrag(p,p.locator('[id="section-folder:s1"]'),p.locator('[id="section-folder:s5"] .section-heading-text'),.95);await expect(p.locator('.drag-status')).toContainText('End of Favorites bar');const edge=await p.locator('.drag-cue').boundingBox(),sheet=await p.locator('[id="card-folder:s5"]').boundingBox();assert(Math.abs(edge.y-(sheet.y+sheet.height-2))<3);await p.mouse.up();await expect.poll(()=>p.evaluate(async()=>(await window.service.snapshot('check')).folders.find(f=>f.id==='r1').children.at(-1).id)).toBe('s1');
 assert.deepEqual(errors,[]);report.push({theme,result:'12px navigation, menus, responsive scopes, modal keyboard, URL inputs, placements, stale deletion, title drag/end geometry and native subtree fixture deletion passed'});await c.close();
}await writeFile(join(fixture.output,'022-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({output:fixture.output,report},null,2));}finally{await browser.close();await new Promise(r=>fixture.server.close(r));}
