import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { extensionId } from './extension-id.mjs';
const manifest = JSON.parse(readFileSync('dist/manifest.json', 'utf8'));
assert.equal(manifest.manifest_version, 3);
assert.equal(extensionId, 'nfhbegeoeafnpejpjdljhgagefbpafal', 'Development identity changed; do not rotate the key accidentally.');
assert.equal(manifest.key, JSON.parse(readFileSync('public/manifest.json', 'utf8')).key);
assert.deepEqual(manifest.permissions, ['bookmarks', 'storage']);
assert.ok(existsSync(`dist/${manifest.chrome_url_overrides.newtab}`));
assert.ok(existsSync(`dist/${manifest.background.service_worker}`));
assert.ok(!readFileSync('dist/index.html', 'utf8').includes('/src/'));
console.log(`MV3 package verified. Development extension ID: ${extensionId}`);
