/* global window, document, structuredClone */
import {chromium,expect} from '@playwright/test';
import {editingFixture} from './editing-fixture.mjs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
import {writeFile} from 'node:fs/promises';
const fixture=await editingFixture({duplicates:true}),browser=await chromium.launch(),report=[];
async function point(locator,fraction=.5){return locator.evaluate((n,f)=>{const rs=[...n.getClientRects()].filter(r=>r.width>0&&r.top>=0&&r.bottom<window.innerHeight),r=rs.at(-1);if(!r)throw Error('No visible title fragment');const line=rs.filter(a=>Math.abs(a.top-r.top)<2),left=Math.min(...line.map(a=>a.left)),right=Math.max(...line.map(a=>a.right));return {x:left+(right-left)*f,y:r.top+r.height/2}},fraction);}
async function begin(p,locator){await locator.scrollIntoViewIfNeeded();const a=await point(locator,.2);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(a.x+10,a.y+2,{steps:3});await expect(p.locator('.drag-preview')).toBeVisible();}
async function target(p,locator,fraction=.5){const a=await point(locator,fraction);await p.mouse.move(a.x,a.y,{steps:12});}
async function evidence(p,label){return p.evaluate(async label=>{const s=await window.service.snapshot(label);return {label,native:s.favorites.map(f=>({id:f.id,title:f.title,url:f.url,parentId:f.parentId,index:f.index})),tags:window.tagEvidence(s),local:s.local.mappings,current:s.reconciliation,records:s.metadata.records,commands:window.commands.filter(c=>c.type==='move'),writes:window.nativeWrites}},label);}
try{for(const theme of ['light','dark']){
 const c=await browser.newContext({viewport:{width:1250,height:950},colorScheme:theme}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));await c.route('https://example.test/**',route=>route.abort());await p.goto(fixture.url);
 await p.locator('#catalogue-edit').click();await p.locator('[id="section-folder:s0"]').click();await p.locator('#folder-source-folder').click();
 const before=await evidence(p,'before UI moves'),trace=[before];
 // Primary click and Enter open the correct native ID editor, not a same-title neighbor.
 await p.locator('#bookmark-dup-a').click();await expect(p.locator('dialog')).toContainText('Native item ID: dup-a');await expect(p.locator('#favorite-edit-tags')).toHaveValue('a-only');await p.keyboard.press('Escape');
 await p.locator('#bookmark-dup-a').focus();await p.keyboard.press('Enter');await expect(p.locator('dialog')).toContainText('Native item ID: dup-a');await p.keyboard.press('Escape');
 // Context menu events remain native/unprevented with a genuine href; OS menu contents need Edge review.
 await p.evaluate(()=>{window.contextEvents=[];document.addEventListener('contextmenu',e=>{window.contextEvents.push({id:e.target.closest('.bookmark-title')?.id,prevented:e.defaultPrevented})})});
 await p.locator('#bookmark-dup-a').click({button:'right'});await p.locator('#bookmark-dup-a').focus();await p.keyboard.press('Shift+F10');assert.equal((await p.evaluate(()=>window.contextEvents)).length,2);assert((await p.evaluate(()=>window.contextEvents)).every(e=>!e.prevented));assert.equal(await p.locator('#bookmark-dup-a').getAttribute('href'),'https://example.test/duplicate');
 // Deliberate modifier/middle navigation remains native in Edit mode.
 for(const action of [{modifiers:['Control']},{button:'middle'}]){const popup=c.waitForEvent('page'),request=c.waitForEvent('request',{predicate:r=>r.url()==='https://example.test/duplicate'});await p.locator('#bookmark-dup-a').click(action);await request;const tab=await popup;await tab.close();await p.bringToFront();await expect(p.locator('dialog')).toHaveCount(0);}
 // Normal browsing follows the unchanged real link.
 const browse=await c.newPage();await browse.goto(fixture.url);await browse.locator('[id="section-folder:s0"]').click();await browse.locator('#folder-source-folder').click();const navigation=c.waitForEvent('request',{predicate:r=>r.url()==='https://example.test/duplicate'});await browse.locator('#bookmark-dup-a').click();await navigation;await browse.close();await p.bringToFront();
 // Immediate feedback on empty space and invalid self destination; no mutations or post-cancel editor.
 await begin(p,p.locator('#bookmark-dup-a'));await target(p,p.locator('.editing-badge')); await expect(p.locator('.drag-preview')).toContainText('Moving Duplicate');await expect(p.locator('.drag-preview')).toContainText('Choose a destination');await expect(p.locator('[data-item-id="dup-a"]')).toHaveAttribute('data-moving','true');await p.screenshot({path:join(fixture.output,`${theme}-moving-empty.png`)});await p.keyboard.press('Escape');await p.mouse.up();await expect(p.locator('.drag-preview')).toHaveCount(0);await expect(p.locator('dialog')).toHaveCount(0);
 // Repeated source moves merge native duplicate locators, then separate again. Input is actual pointer movement.
 for(let cycle=0;cycle<3;cycle++){
   if(!await p.locator('#bookmark-dup-a').isVisible())await p.locator('#folder-source-folder').click();
   await begin(p,p.locator('#bookmark-dup-a'));await p.evaluate(()=>window.refresh());await p.waitForTimeout(180);await target(p,p.locator('#folder-destination-folder'));await expect(p.locator('.drag-status')).toContainText('Move inside Destination');await p.mouse.up();
   await expect.poll(()=>p.evaluate(async()=>(await window.service.snapshot('native move event')).favorites.find(f=>f.id==='dup-a').parentId)).toBe('destination-folder');await expect(p.locator('dialog')).toHaveCount(0);trace.push(await evidence(p,`duplicate parent ${cycle}`));
   await p.locator('#folder-destination-folder').click();await expect(p.locator('#bookmark-dup-a')).toBeVisible();await p.locator('#bookmark-dup-a').click();await expect(p.locator('#favorite-edit-tags')).toHaveValue('a-only');await expect(p.locator('dialog')).toContainText('#destination-inherited');await expect(p.locator('#favorite-edit-title')).toBeEditable();await p.keyboard.press('Escape');
   // Same-parent reorder before the other duplicate, with native IDs retained.
   await begin(p,p.locator('#bookmark-dup-a'));await target(p,p.locator('#bookmark-dup-b'),.1);await expect(p.locator('.drag-status')).toContainText('Insert before');await expect(p.locator('.drag-cue')).toHaveCSS('width','2px');await p.mouse.up();await expect.poll(()=>p.evaluate(async()=>(await window.service.snapshot('reordered')).folders.find(f=>f.id==='destination-folder').children[0].id)).toBe('dup-a');trace.push(await evidence(p,`reordered ${cycle}`));
   await begin(p,p.locator('#bookmark-dup-a'));await target(p,p.locator('#folder-source-folder'));await p.mouse.up();await expect.poll(()=>p.evaluate(async()=>(await window.service.snapshot('back')).favorites.find(f=>f.id==='dup-a').parentId)).toBe('source-folder');trace.push(await evidence(p,`returned ${cycle}`));
 }
 // Same-title/different-URL item also moves without merging either duplicate.
 await begin(p,p.locator('#bookmark-dup-c'));await target(p,p.locator('#folder-source-folder'));await p.mouse.up();await expect.poll(()=>p.evaluate(async()=>(await window.service.snapshot('different URL move')).favorites.find(f=>f.id==='dup-c').parentId)).toBe('source-folder');trace.push(await evidence(p,'same title different URL'));
 // A rejected native move cleans up feedback and never triggers a title click.
 await p.evaluate(()=>window.failMove=true);await begin(p,p.locator('#bookmark-dup-b'));await target(p,p.locator('#folder-source-folder'));await p.mouse.up();await expect(p.locator('.status-error').first()).toContainText('Synthetic move failure');await expect(p.locator('.drag-preview')).toHaveCount(0);await expect(p.locator('dialog')).toHaveCount(0);await p.evaluate(()=>window.failMove=false);
 const after=await evidence(p,'after repeated moves');const immutable=nodes=>nodes.map(({id,title,url})=>({id,title,url})).sort((a,b)=>a.id.localeCompare(b.id));assert.deepEqual(immutable(after.native),immutable(before.native));assert.deepEqual(after.records,before.records);assert(after.writes.every(w=>w.operation==='move'));for(const state of trace){for(const id of ['dup-a','dup-b','dup-c'])assert.equal(state.current.mappings[id]?.stableId,before.current.mappings[id].stableId);assert(!state.current.matches.some(m=>m.status==='ambiguous'));const a=state.native.find(n=>n.id==='dup-a');assert.deepEqual(state.tags['dup-a'].effective,['a-only',a.parentId==='source-folder'?'source-inherited':'destination-inherited']);assert.equal(state.tags['dup-a'].sources[0].id,a.parentId);}
 // Dirty draft remains blocked, read-only and recoverable when genuine competing identity arrives.
 await p.locator('#folder-source-folder').click();await p.locator('#bookmark-dup-a').click();await p.locator('#favorite-edit-title').fill('Unsaved draft');await p.evaluate(()=>{const r=structuredClone(window.sync.data['meta:00000000-0000-4000-8000-000000000001']);r.stableId='00000000-0000-4000-8000-000000000099';window.sync.data['meta:'+r.stableId]=r;window.refresh()});await expect(p.locator('#favorite-metadata-status')).toContainText('Ambiguous metadata');await expect(p.locator('#favorite-edit-title')).toHaveValue('Unsaved draft');await expect(p.locator('#favorite-edit-title')).not.toBeEditable();await expect(p.getByRole('button',{name:'Save',exact:true})).toBeDisabled();await expect(p.locator('#favorite-edit-tags')).toHaveValue('a-only');await p.locator('#favorite-edit-title').focus();await p.keyboard.press('Shift+Tab');await expect(p.locator('.identity-details:has(pre) summary')).toBeFocused();await p.keyboard.press('Enter');await expect(p.locator('.identity-details pre')).toBeVisible();await p.keyboard.press('Enter');await p.keyboard.press('Tab');await expect(p.locator('#favorite-edit-title')).toBeFocused();await p.screenshot({path:join(fixture.output,`${theme}-blocked-draft.png`)});await p.keyboard.press('Escape');await p.keyboard.press('Escape');await expect(p.locator('#favorite-edit-title')).toHaveValue('Unsaved draft');await p.keyboard.press('Escape');await p.getByRole('button',{name:'Discard changes',exact:true}).click();
 await expect(p.locator('[data-item-id="dup-a"] .status-annotation')).toContainText('Ambiguous metadata');await p.locator('#bookmark-dup-a').click();await expect(p.locator('#favorite-edit-title')).not.toBeEditable();await expect(p.locator('#favorite-edit-tags')).toHaveValue('');await expect(p.locator('#favorite-metadata-status')).toContainText('not an empty assignment');await p.keyboard.press('Escape');
 // The other duplicate is inspected by ID, never assumed to be the ambiguous favorite.
 await p.locator('#folder-destination-folder').click();await p.locator('#bookmark-dup-b').click();await expect(p.locator('dialog')).toContainText('Native item ID: dup-b');await expect(p.locator('#favorite-edit-title')).toBeEditable();await expect(p.locator('#favorite-edit-tags')).toHaveValue('b-only');await p.keyboard.press('Escape');
 // Remove ONLY the deliberately injected conflicting record in this isolated fixture, then section cues.
 await p.evaluate(()=>{delete window.sync.data['meta:00000000-0000-4000-8000-000000000099'];window.refresh()});await p.waitForTimeout(220);await p.locator('[id="section-folder:s0"]').click();
 await begin(p,p.locator('[id="section-folder:s2"]'));await target(p,p.locator('[id="section-folder:s0"] .section-heading-text'),.05);await expect(p.locator('.drag-status')).toContainText('Insert before Design 0 in Favorites bar');const line=await p.locator('.drag-cue').boundingBox();assert(line.width>500&&line.height===2);await p.screenshot({path:join(fixture.output,`${theme}-section-before.png`)});await p.keyboard.press('Escape');await p.mouse.up();
 await begin(p,p.locator('[id="section-folder:s1"]'));await target(p,p.locator('[id="section-folder:s1"] .section-heading-text'));await expect(p.locator('.drag-preview')).toContainText('Not allowed');await p.keyboard.press('Escape');await p.mouse.up();
 await p.setViewportSize({width:390,height:950});await p.locator('[id="section-folder:s0"]').click();await p.locator('#folder-source-folder').click();await begin(p,p.locator('#bookmark-dup-a'));await p.mouse.move(370,650,{steps:5});await p.screenshot({path:join(fixture.output,`${theme}-narrow-preview.png`)});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await p.keyboard.press('Escape');await p.mouse.up();await expect(p.locator('.drag-preview')).toHaveCount(0);await expect(p.locator('dialog')).toHaveCount(0);
 await writeFile(join(fixture.output,`${theme}-identity-trace.json`),JSON.stringify(trace.map(row=>({...row,nativeCount:row.native.length,allNativeContentSHA256:createHash('sha256').update(JSON.stringify(immutable(row.native))).digest('hex'),native:row.native.filter(n=>['dup-a','dup-b','dup-c','distinct'].includes(n.id)),tags:Object.fromEntries(Object.entries(row.tags).filter(([id])=>['dup-a','dup-b','dup-c','distinct','source-folder','destination-folder'].includes(id)))})),null,2));assert.deepEqual(errors,[]);report.push({theme,moves:after.writes.length,result:'pointer duplicate moves/reorders preserve native IDs/title/URL/direct metadata; editor health/draft, immediate preview, section lines, click/Enter and native context-event checks passed'});await c.close();
}await writeFile(join(fixture.output,'023-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({output:fixture.output,report},null,2));}finally{await browser.close();await new Promise(r=>fixture.server.close(r));}
