/* global window, getComputedStyle */
import {chromium,expect} from '@playwright/test';
import {editingFixture} from './editing-fixture.mjs';
import {writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import assert from 'node:assert/strict';
const f=await editingFixture({workspace:true}),browser=await chromium.launch(),reports=[];
try{for(const theme of ['light','dark']){
 const p=await browser.newPage({viewport:{width:1200,height:900},colorScheme:theme});const errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto(f.url);
 const area=name=>p.locator('.manage-navigation').getByRole('button',{name:new RegExp('^'+name)});
 await p.getByRole('button',{name:'Manage',exact:true}).click();await expect(p.getByRole('heading',{name:'Indexfold',exact:true})).toBeFocused();await expect(p.locator('.manage')).toContainText('Your bookmarks, beautifully within reach.');await expect(p.locator('code').filter({hasText:'chrome://extensions/shortcuts'})).toBeVisible();await p.getByLabel('Show archived',{exact:true}).check();await p.screenshot({path:join(f.output,`${theme}-settings.png`)});await p.setViewportSize({width:390,height:850});await p.screenshot({path:join(f.output,`${theme}-settings-narrow.png`)});await p.setViewportSize({width:1200,height:900});
 await area('Bookmarks').click();await p.getByRole('button',{name:'New bookmark',exact:true}).click();await p.getByLabel('Title',{exact:true}).fill('Retained draft');await area('Diagnostics').click();await expect(p.getByText('Your bookmark draft is retained.')).toBeVisible();await expect(p.getByRole('button',{name:'Export diagnostic JSON'})).toBeVisible();await expect(p.getByText('0.1.26',{exact:false}).first()).toBeVisible();await p.screenshot({path:join(f.output,`${theme}-diagnostics.png`)});await area('Settings').click();await p.getByLabel('Appearance',{exact:true}).selectOption(theme);await area('Bookmarks').click();await expect(p.getByLabel('Title',{exact:true})).toHaveValue('Retained draft');await p.screenshot({path:join(f.output,`${theme}-bookmarks.png`)});
 await p.getByRole('button',{name:'Back to dashboard'}).click();await expect(p.locator('#catalogue-manage')).toBeFocused();await p.getByRole('button',{name:'Manage',exact:true}).click();await expect(p.getByLabel('Title',{exact:true})).toHaveValue('Retained draft');await p.getByRole('button',{name:'Back to dashboard'}).click();
 await p.locator('#catalogue-edit').click();await p.getByRole('button',{name:'Espaces de travail',exact:true}).click();
 await p.locator('#edit-folder-ws-container').click();await expect(p.locator('#favorite-edit-title')).toHaveAttribute('readonly','');await expect(p.locator('#favorite-edit-tags')).toBeEditable();await expect(p.getByText('Read-only',{exact:true})).toBeVisible();await expect(p.getByText('Native item ID: ws-container',{exact:true})).toBeHidden();
 const readonly=await p.locator('#favorite-edit-title').evaluate(n=>getComputedStyle(n).backgroundColor),editable=await p.locator('#favorite-edit-tags').evaluate(n=>getComputedStyle(n).backgroundColor);assert.notEqual(readonly,editable);await p.screenshot({path:join(f.output,`${theme}-readonly.png`)});await p.locator('#favorite-edit-tags').fill('source');await p.getByRole('button',{name:'Save',exact:true}).click();assert.equal(await p.evaluate(()=>window.nativeWrites.length),0);
 await p.locator('#edit-folder-ws-second').click();await p.locator('#favorite-edit-tags').fill('destination');await p.getByLabel('Archive this folder and its contents').check();await p.getByRole('button',{name:'Save',exact:true}).click();
 const menuButton=p.getByRole('button',{name:'More actions for Projet',exact:true});await menuButton.click();const menu=p.locator('.item-menu:popover-open');await expect(menu.getByRole('menuitem',{name:'Move…'})).toHaveCount(0);await expect(menu).not.toContainText('Workspace naming');const row=menu.getByRole('menuitem',{name:'New bookmark'});await row.hover();assert.notEqual(await row.evaluate(n=>getComputedStyle(n).backgroundColor),'rgba(0, 0, 0, 0)');await p.keyboard.press('ArrowDown');await expect(menu.getByRole('menuitem',{name:'New folder'})).toBeFocused();await p.setViewportSize({width:390,height:850});let resized=await menu.boundingBox();assert(resized.x>=0&&resized.x+resized.width<=390);await p.keyboard.press('Escape');await menuButton.click();await expect.poll(()=>menu.evaluate(n=>n.scrollWidth<=n.clientWidth)).toBe(true);const box=await menu.boundingBox();assert(box.x>=0&&box.x+box.width<=390);await p.screenshot({path:join(f.output,`${theme}-menu-narrow.png`)});await p.keyboard.press('Escape');await expect(menuButton).toBeFocused();await p.setViewportSize({width:1200,height:900});
 await p.locator('[data-section-id="folder:ws-container"] .section-toggle').click();await p.locator('#folder-ws-folder').click();await p.locator('#edit-bookmark-ws-link').click();await p.locator('#favorite-edit-tags').fill('own');await p.getByRole('button',{name:'Save',exact:true}).click();
 const before=await p.evaluate(async()=>{const s=await window.service.snapshot('before');return {id:s.reconciliation.mappings['ws-link'].stableId,title:s.favorites.find(n=>n.id==='ws-link').title,url:s.favorites.find(n=>n.id==='ws-link').url};});
 await p.getByRole('button',{name:'More actions for Notes',exact:true}).click();await p.getByRole('menuitem',{name:'Move…'}).click();await p.locator('#move-parent').selectOption('ws-second');await p.evaluate(()=>window.silentMove=true);await p.getByRole('button',{name:'Move',exact:true}).click();await expect(p.locator('dialog')).toContainText('native position is unchanged');assert.equal(await p.evaluate(()=>window.nativeWrites.filter(n=>n.operation==='move').length),0);await p.evaluate(()=>window.silentMove=false);await p.getByRole('button',{name:'Move',exact:true}).click();await expect(p.locator('dialog')).toHaveCount(0);
 const moved=await p.evaluate(async()=>{const s=await window.service.snapshot('moved'),tags=window.tagEvidence(s)['ws-link'];return {id:s.reconciliation.mappings['ws-link'].stableId,title:s.favorites.find(n=>n.id==='ws-link').title,url:s.favorites.find(n=>n.id==='ws-link').url,parent:s.folders.find(n=>n.id==='ws-folder').parentId,tags};});assert.equal(moved.parent,'ws-second');assert.equal(moved.id,before.id);assert.equal(moved.title,before.title);assert.equal(moved.url,before.url);assert.deepEqual(moved.tags.effective,['archived','destination','own']);
 // Actual pointer drag back across container boundary. No copy/delete or title updates.
 const section=p.locator('[data-section-id="folder:ws-second"] .section-toggle');if(await section.getAttribute('aria-expanded')!=='true')await section.click();const folder=p.locator('#folder-ws-folder');if(await folder.getAttribute('aria-expanded')!=='true')await folder.click();const source=p.locator('#bookmark-ws-link');await source.scrollIntoViewIfNeeded();const point=await source.evaluate(n=>{const r=n.getClientRects()[0];return{x:r.x+6,y:r.y+r.height/2};});await p.mouse.move(point.x,point.y);await p.mouse.down();await p.mouse.move(point.x+12,point.y,{steps:3});await expect(p.locator('.drag-preview')).toContainText('Moving Workspace favorite');const target=p.locator('[data-section-id="folder:ws-container"] .section-title-text');const rect=await target.boundingBox();await p.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2,{steps:12});await expect(p.locator('.drag-status')).toContainText('Move inside');await p.mouse.up();await expect.poll(()=>p.evaluate(async()=>(await window.service.snapshot('pointer')).favorites.find(n=>n.id==='ws-link').parentId)).toBe('ws-container');
 assert.deepEqual(await p.evaluate(async()=>window.tagEvidence(await window.service.snapshot('inherited'))['ws-link'].effective),['own','source']);assert.equal(await p.evaluate(()=>window.nativeWrites.filter(n=>n.operation==='move').length),2);
 await p.emulateMedia({forcedColors:'active'});await p.locator('#edit-folder-ws-container').click();await expect(p.locator('#favorite-edit-title')).toHaveAttribute('readonly','');assert.equal(await p.locator('#favorite-edit-title').evaluate(n=>getComputedStyle(n).borderBottomStyle),'dashed');await p.keyboard.press('Escape');assert.deepEqual(errors,[]);
 reports.push({theme,result:'Manage panels/draft/focus, protected controls, menu keyboard/hover/narrow, cross-container subtree and real pointer bookmark moves with native values/identity/direct tags and recomputed inheritance, forced colors passed'});await p.close();
}await writeFile(join(f.output,'026-report.json'),JSON.stringify(reports,null,2));console.log(f.output);}finally{await browser.close();f.server.close();}
